# Generated by Django 5.2.8 on 2025-11-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openlibrary_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=300)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True)),
            ],
        ),
    ]
